### ISSUE TITLE
Not able to install on AWS linux

### ISSUE THREAD

**Issue by jtalfresco** [Alfresco/generator-ng2-alfresco-app#22]
When I run npm install after generating the app, it throws a large amount of WARNS (see log.txt)
[log.txt](https://github.com/Alfresco/generator-ng2-alfresco-app/files/480925/log.txt)

When I then run npm start, it doesn't work properly and outputs the following: 
[npmstart.txt](https://github.com/Alfresco/generator-ng2-alfresco-app/files/480927/npmstart.txt)

Is this expected behavior? When I follow the same steps on my Mac, it works as expected.

I'm using npm 3.10.3 version and nodejs version 6.6.0

**Comment by magemello** [comment]
Hi,

The warnings shouldn't be a problem. Instead of 'npm start' can you try executing :

`
npm run serve
`

Thank you

**Comment by jtalfresco** [comment]
Hello Mario,

This is the output when I run that:
`$ npm run serve

> test@0.1.0 serve /home/ec2-user/test
> wsrv -o -s -l -p 3000 -x ./server/versions.js

Server running at: http://localhost:3000
Opening start page: http://localhost:3000
(node:3712) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3`

**Comment by DenisVuyka** [comment]
@jtalfresco I think the issue is related to `npm start` script, it tries opening default browser when you are probably running a headless linux configuration. For testing purposes I would suggest removing `-o` (open browser) and `-l` (live reload) switches. 

Please note that `npm start` is mainly developer-oriented, you may need something more complex for production.

**Comment by jtalfresco** [comment]
Thank you for the help. Once I did that and defined the host with -a, it worked.
